name = "DebugArtifacts"
uuid = "4f05f810-3073-4646-a23d-fd50056b1323"
authors = ["Mosè Giordano"]
version = "0.1.0"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
